### PR TITLE
From stream

### PR DESCRIPTION
**Pull request by operandom**
### Things done:
- update dependencies,
- use of rollup-plugin-vinyl to get content from gulp stream,
- add jsDoc comments,
- remove rollup dependencies to let the user choose himself the version.

### Todo:
- could be good to have a dev branch to test before put changes in master
- perhaps add some more tests

### CODE REVIEW

**Comment by Permutatrix** [comment]
You certainly made yourself nice and cozy. We're not looking to read the entry file from the Vinyl stream, though. See #16. As a matter of fact, this plugin is blacklisted by gulp, and with good reason. You should use [rollup-stream](https://github.com/permutatrix/rollup-stream) instead.

**Comment by operandom** [comment]
Hi @Permutatrix,

Thanks for your warm welcome !

I know that gulp-rollup is blacklisted and my understanding of the reasons is that your plugin breaks the rules of gulp, it breaks the stream and reads files from the filesystem as @phated said [here](https://github.com/mcasimir/gulp-rollup/pull/16#issuecomment-156866698).

> We typically blacklist plugins that try to abstract bundlers because the bundlers are doing the reading from the filesystem instead of taking file contents (filesystem reading is against the plugin guidelines).

I just tried to make your plugin fit the gulp rules because what @TrySound and @ben-eb describe [here](https://github.com/mcasimir/gulp-rollup/pull/16#issuecomment-156672115) and [here](https://github.com/mcasimir/gulp-rollup/pull/16#issuecomment-156682216) is excactly what I also need.

```javascript
gulp.task('default', function () {
  return gulp.src('src/main.js')
    .pipe(sourcemaps.init())
    // Some plugins
    .pipe(rollup())
    // Some others plugins
    .pipe(sorucemaps.write('.'))
    .pipe(gulp.dest('dist'));
});
```

I just [added the sourcemaps chaining](https://github.com/operandom/gulp-rollup/commit/56e1dca26f01d481913a405326ac29d55557ea25). It's certainly not perfect but it seems to work for me.

I'm  sorry if you don't want these changes, I thought it would be better to contribute to your repository. This seemed to be more legitimate to me as you had already started working on it.

**Comment by TrySound** [comment]
@operandom What is the case of using streams with rollup?

**Comment by operandom** [comment]
@TrySound I'm working on some file providers (not finished yet) and the contents don't come from the file sytem.

For me, getting the contents of files and transforming them shouldn't be done by a same gulp plugin because it reduces the possibilities and what I love with gulp is its modularity and its adaptability.

**Comment by TrySound** [comment]
@operandom But gulp has stream overhead. rollup API is much simple.

**Comment by Permutatrix** [comment]
@operandom It's fine. One problem with your/@TrySound's model is that it still breaks the gulp plugin guidelines, since files other than the entry still need to be loaded directly from the filesystem. It's not the only problem, as you can see in #16's discussion.

If you need to process files using gulp plugins before passing them to Rollup, you can check to see if my [rollup-plugin-gulp](https://www.npmjs.com/package/rollup-plugin-gulp) will serve your purpose. I imagine it will if you just want to transform the entry file, since you can use `options.include` to ensure that only that one file is processed.

If that doesn't do what you need, though, [see if my ideas for gulp-rollup v2 fit the bill](https://github.com/mcasimir/gulp-rollup/pull/16#issuecomment-156668598). I haven't had sufficient motivation to actually implement it yet, but if you have a use case that isn't covered by rollup-stream and rollup-plugin-gulp, maybe I'll finally get that done and get this plugin unblacklisted.

**Comment by Permutatrix** [comment]
@operandom If you need to synthesize files to feed to Rollup, the simplest solution is probably to make a Rollup plugin as @TrySound suggests.

**Comment by operandom** [comment]
@Permutatrix After some reading, I'm not sure that my pull request breaks the gulp rules anymore. For exemple gulp-browserify is black listed but gulp-useref is not. Both of them touch the fs.

I like your V2, I think we can block the calls to fs from rollup if it's a problem for gulp team (something like [that](https://github.com/contra/gulp-concat/blob/master/index.js#L74) with a test on ids).

The rollup plugin is not a bad idea but I really like gulp. : /

**Comment by Permutatrix** [comment]
@operandom I'd say the critical difference in gulp-useref is that it's perfectly capable of operating entirely within gulp streams&mdash;you just have to use `options.additionalStreams`. Of course, gulp-useref will poke around in your filesystem anyway for no reason because gulp-useref seems to be pretty terrible, but you can only tell by looking at its code. You can control all of the input and output from within gulp. Being able to _not_ specify `options.additionalStreams` is just a matter of convenience.

But it doesn't really matter whether this PR breaks the plugin guidelines. I firmly held my stance on this kind of functionality before the plugin was even added to the blacklist. Making gulp-rollup read the entry file and only the entry file from the stream is, simply put, a terrible idea. I'll see what I can do about making gulp-rollup v2 happen.

**Pull request closed without merging**
