### PR TITLE
Use rollup-plugin-memory to load entries from stream

### PR DESCRIPTION
**Pull request by TrySound**

### CODE REVIEW

**Comment by Permutatrix** [comment]
If I'm not mistaken, this would render the plugin incapable of rolling anything up, since Rollup wouldn't have access to any files other than the entry.

The idea of using buffers has merit, and I have some ideas for how to implement it, but not this, not at all. Sorry.

I'm in a bit of a hurry, so I can't elaborate further at the moment.

**Comment by TrySound** [comment]
@Permutatrix Don't understand your misunderstanding. Only entry file will be loaded from the memory. Everything other will be as usual.

**Comment by Permutatrix** [comment]
Got it. Still, it would be better to be able to control all of the files, right? Like so:

```js
var gulp       = require('gulp'),
    rollup     = require('gulp-rollup');

gulp.task('bundle', function(){
  gulp.src('src/**/*')
    .pipe(rollup({
        entry: 'src/main.js'
    }))
    .pipe(gulp.dest('dist'));
});
```

That's what I thought of when I first saw your issue.

**Comment by TrySound** [comment]
@Permutatrix Nope.The idea of the gulp is input from memory and output in memory. What if need to process a few files by one task? This is gulpy way. You suggest some weird and unexpected way. Users should just put it in pipe and don't think about any entry.

**Comment by Permutatrix** [comment]
Yes, exactly. And I love that way of doing things. With my version, _all_ files are input and output in memory, not just the entry. Perhaps you're misunderstanding my example? I'll add comments:

```js
var gulp       = require('gulp'),
    rollup     = require('gulp-rollup');

gulp.task('bundle', function(){
  // load all files from src into memory.
  gulp.src('src/**/*')
    // here you can modify the files if you want.

    // gulp-rollup takes in files and builds a table of them, a sort of
    // "virtual filesystem".
    .pipe(rollup({
        // it then tells rollup to use this file within the virtual filesystem
        // as the entry point. you can supply an array instead if you like,
        // in which case multiple output files will be emitted.
        entry: 'src/main.js'
    }))
    // and pipe the result to dist as normal.
    .pipe(gulp.dest('dist'));
});
```

**Comment by TrySound** [comment]
@Permutatrix This is not expectable behaviour. I'd like the idea that rollup should own process files inside. But the entry should be loaded by gulp. It's UX

**Comment by Permutatrix** [comment]
But what if you want to put all of the files through a preprocessor before rolling them up? That would be impossible with your method.

If you want a super simple interface, you use gulp-rollup; if you want a marginally more sophisticated interface with complete control over your input, you use gulp-rollup-buffers. There's no reason to make any compromises just to make the interface slightly easier to use.

**Comment by TrySound** [comment]
@Permutatrix Yeah okay gulp-rollup-buffers is cool, but I don't need this. I want just pass a few entries in gulp-rollup without fear that gulp-rollup is not first in pipeline and without necessary `{read: false}` option in gulp.src. It's very ugly solution. Users expect only entry file loading, nothing more.

**Comment by Permutatrix** [comment]
Okay, what are you trying to accomplish here, exactly? Why do you need to be able to pass in the entry file from memory but not any of the others?

**Comment by TrySound** [comment]
@Permutatrix Yep.
Ideal way:
```
gulp.task('script', function () {
  return gulp.src('src/main.js')
    .pipe(sourcemaps.init())
    .pipe(rollup())
    .pipe(sorucemaps.write('.'))
    .pipe(gulp.dest('dist'));
});
```

**Comment by Permutatrix** [comment]
Why?

**Comment by TrySound** [comment]
@Permutatrix Caz it's user expirience

**Comment by TrySound** [comment]
Rollup arch is the same that we able to do normal plugin without understanding troubles.

**Comment by TrySound** [comment]
@Permutatrix Less api is better api. Why you don't want make it simpler?

**Comment by Permutatrix** [comment]
But it makes things work in a weird, idiosyncratic, non-self-evident way. The way gulp-rollup currently works is simple and explicit: you use Vinyl to _mark out_ a file, which Rollup then uses as it normally would. We shouldn't try to shoehorn this plugin into working with buffers without giving it an interface where that actually makes sense, you know? It's like how you're not supposed to read streams into buffers just to make your plugin work with streams.

**Comment by Permutatrix** [comment]
How is your version simpler?

**Comment by TrySound** [comment]
@Permutatrix There is no {read: false} and I don't care about rollup position in pipeline. Much simpler

**Comment by Permutatrix** [comment]
Neither of those things simplifies the API. `{read: false}` isn't mandatory; it's just for efficiency, and look, passing options to functions isn't exactly a big deal. And if you want to put Rollup at any position in the pipeline other than the beginning, you're generally going to want to use gulp-rollup-buffers; position in the pipeline isn't something you have to worry about because you control it from start to finish.

**Comment by TrySound** [comment]
@Permutatrix Why create too much unncessary things? Who need that? What's the problem? Why do not make it efficient without passing any options? We can do it. Why you don't want? It works the same way. But loads entry from memory. Nothing breaks. Everything is file!

**Comment by Permutatrix** [comment]
It's like I said in [my earlier comment](https://github.com/mcasimir/gulp-rollup/pull/16#issuecomment-156672608): shoehorning things into using systems that don't make sense for them is bad. It's a great way to produce weird bugs and unexpected behavior.

The way gulp-rollup works right now is extremely simple and transparent. You can tell exactly how it works just by looking at an example of it in use. That's how a gulp plugin that accomplishes a simple task is supposed to be. I don't support the idea of adding arcane functionality just to eliminate the "need" to pass a single parameter into gulp.src.

**Comment by Permutatrix** [comment]
Sorry if I seem cranky, by the way. It's 1:15 a.m. where I am.

**Comment by Permutatrix** [comment]
Uh... This is ominous. What are you doing, exactly?

**Comment by Permutatrix** [comment]
Well, I'm going to bed. I guess I'll see what these folks have to say on the matter tomorrow. Should be interesting.

**Comment by ben-eb** [comment]
Users shouldn't have to worry about implementation details for a gulp plugin. That's the whole point of using gulp, that everything uses a normalised API and tools can be connected together like Lego. Therefore, creating gulp-rollup-buffers means confusing users between two different versions of a tool that should already work in a *consistent* way with their existing tasks.

IMO, this has a much clearer API:

```js
gulp.task('default', function () {
  return gulp.src('src/main.js')
    .pipe(sourcemaps.init())
    .pipe(rollup())
    .pipe(sorucemaps.write('.'))
    .pipe(gulp.dest('dist'));
});
```

Than this:

```js
gulp.task('default', function () {
  return gulp.src('src/main.js')
    .pipe(rollup({
        sourceMap: true
    }))
    .pipe(sourcemaps.write("."))
    .pipe(gulp.dest('dist'));
});
```

As it works *exactly like* all other plugins that provide gulp-sourcemaps support.

**Comment by Permutatrix** [comment]
Interesting point about the sourcemaps. Honestly, though, that seems like a deficiency in gulp-sourcemaps to me; why doesn't it allow null files to have sourcemaps? Reading entry files as buffers to solve this problem would be a hack, though I suppose if gulp-sourcemaps doesn't change that behavior it may be a necessary one.

And I must heartily disagree with the point about gulp-rollup-buffers. It would allow the user to do useful things that aren't possible with the original version of the plugin, and I don't see what's so difficult or un-"gulpy" about its API. If only one version of the plugin is allowed to stay, I say that should be the one.

And the users aren't stupid, anyway. If the very simple cases where gulp-rollup and gulp-rollup-buffers should be used are explained in the README, they'll be able to figure it out, right? Then again, I'm not the most experienced in making tools like this, so I could be wrong.

**Comment by Permutatrix** [comment]
@ben-eb

**Comment by ben-eb** [comment]
I didn't mean to infer that users are stupid; users of gulp are developers after all. The point is that the sourcemaps API is already clearly defined, and whether it has deficiencies or not is irrelevant because it's how a developer would expect to use sourcemaps with gulp.

[Look at this list](https://github.com/floridoo/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support) and the API documentation for sourcemaps. *It's the same across all modules*. This harmonious API means that once a developer uses gulp-sourcemaps then she can reasonably expect that it will work the same for another tool, without having to even look at the readme. gulp-rollup is the exception to that rule.

`null` files should not have sourcemaps because they are `null`. `null` is `null` and not `{map: 'AAXaB34q...'}`. That is also irrelevant. :wink:

You should not be afraid to break your API to accommodate this patch, it is a much more reasonable and intuitive behaviour than the current release.

**Comment by TrySound** [comment]
@Permutatrix Also reading from buffers is not a hack. It's just adapting one API to another one.

**Comment by Permutatrix** [comment]
@ben-eb There are a number of misunderstandings here.

I know gulp-sourcemaps has a clearly-defined API and everything should use it the same way. I'm all for that. I initially didn't like the PR that added sourcemap support because its API was idiosyncratic; I only ended up accepting it because I thought it was technically impossible to do it correctly with Rollup. I'm actually kind of offended at this one because making libraries work elegantly and in harmony with each other is one of the most central tenets of my programming philosophy.

This discussion wasn't even about sourcemaps, actually. It was about making gulp-rollup load entry files from buffers instead of pointing to them with null Vinyl files. And that's where the second misunderstanding comes in.

A "null file" in Vinyl isn't literally a null value; it's just a file that hasn't been read into memory and doesn't have a stream associated with it. It's basically gulp's way of representing filesystem paths. It should be able to have a sourcemap because it might be transformed in a way that makes one necessary, as evidenced by this very plugin, which currently works by passing the path of a null file into Rollup as the entry point.

I'm not afraid to break the API. I'm not even slightly opposed to making sourcemaps work like they do everywhere else. I just don't like TrySound's proposition that we load entry files, and only entry files, as buffers from gulp's file stream.

I'm sorry for being so brusque, but by no fault of yours, I'm beginning to lose my patience. Having a debate on the Internet is really taxing.

**Comment by Permutatrix** [comment]
@TrySound I've given a number of reasons why I don't want to use buffers for entry files. Doing so anyway in order to work around the behavior of another tool would be a hack.

**Comment by TrySound** [comment]
@Permutatrix Programming is a hack!

**Comment by Permutatrix** [comment]
@TrySound

>Reading entry files as buffers to solve this problem would be a hack, though I suppose if gulp-sourcemaps doesn't change that behavior it may be a necessary one.

If we need a hack, we need a hack. But it's best to try to minimize the damage, so I'm considering what options there are.

**Comment by TrySound** [comment]
@Permutatrix Heh, hack. Okay, let's start the party.

Do you know how works rollup?
`options.entry` is just a start point like. It's APIed `import 'path'` one. So, it's just a path, not a file.
What's inside? Plugins. Default plugins. Start point is resolved by default resolver, then file with this path is loaded by default loader. Defaults is just suggestion, not rule. They can be overrided. This happend in browser version.

So WTF public api and overriding defaults is a hack?

Gulpy way is input and output in the memory. What plugin do with fs inside is not interesting. But input and output should be in memory for usual and expectable api. rollup gives us API for input and output in the memory. But you thought up some reasons that it's not right.

As you said
> Then again, I'm not the most experienced in making tools like this, so I could be wrong.


https://www.npmjs.com/package/gulp-babel
> Why load this from buffer if I can use transformFile that's much cleaner

https://www.npmjs.com/package/gulp-concat
> Let's break the system and make also src/dest options. That will be very Grunty!

**Comment by TrySound** [comment]
Sorry for roughness. It's 4 a.m. now :)

**Comment by Permutatrix** [comment]
@TrySound The party has been going on for far too long already. I've seen things your way. Now I want you to see things my way.

Yes, `options.entry` isn't a file, it's a path, but it isn't just a suggestion. You can't pretend it doesn't exist. Rollup doesn't just deal with files; it deals with paths, too.

Yes, the entry file just so happens to be the first file Rollup loads. But in reality, it's loaded just like every other file. It has a path, and any imports it makes are relative to that path. Furthermore, it is cached in memory as the file that path leads to, so if anything imports the module at the path specified by `options.entry`, it will receive the first file loaded, since that's supposed to be the file at that location. Rollup's input files are modules, and modules are inextricably linked to their paths. It's not about "this is the entry file". It's about "this is the module at this path".

When you use a buffer for the entry file but none of the others, it becomes a special case. But why? It's not a configuration file made of data that can float around wherever it wants to; it's a module just like all the others, and it has to have a definite path like all the others.

gulp-rollup should give Rollup a consistent filesystem to work with, either pure Vinyl or pure direct file access. There's no reason for the entry file to be different.

And please don't take my words out of context like that. I'm the one who wrote them; obviously I remember that I was talking about the ease of use of npm packages, not programming philosophy.

Finally, gulp-babel and gulp-concat are different from gulp-rollup. They operate on independent, abstract chunks of code, not modules that are fundamentally tied to their paths.

Please tell me you see me point now. I just want to be done with this discussion. :(

**Comment by phated** [comment]
After reading this thread and looking at the API defined, it seems to go against standard gulp practices.  Typically, using `gulp.src` strictly for globbing is frowned upon.  This module should probably be replaced in favor of `glob.sync` and passing the paths to rollup directly.  We typically blacklist plugins that try to abstract bundlers because the bundlers are doing the reading from the filesystem instead of taking file contents (filesystem reading is against the plugin guidelines).

**Comment by Permutatrix** [comment]
@phated Thinking about it, you're right. It would be better to give Rollup a gulp-friendly interface that can be used with vinyl-source-stream like Browserify has. It could even be useful for more than just gulp that way.

...I feel enlightened.

**Comment by phated** [comment]
@Permutatrix :+1:

**Comment by TrySound** [comment]
@phated  :+1:

**Comment by TrySound** [comment]
@phated By the way rollup can take file contents with my plugin.

**Pull request closed without merging**
